### ISSUE TITLE
Missing required parameters: either two *_positive_examples or one *_positive_examples and one negative_examples must be provided

### ISSUE THREAD

**Issue by walmon** [watson-developer-cloud/visual-recognition-nodejs#176] opened 2016-06-28 14:20 UTC
I forked the code as it comes, changed the api key, tested that classifying works but when I try to create a new model get this error:
Missing required parameters: either two *_positive_examples or one *_positive_examples and one negative_examples must be provided

I'm sending a positive and negative file, it's working on online demo.

**Comment by nfriedly** [comment] 2016-06-28 17:55
That's strange. No changes to the code at all?

**Comment by walmon** [comment] 2016-06-28 18:00
Yes, no code changes. I created a workaround, the symptoms pointed to a misunderstanding between UI and backend.

The files were getting to the backend, but was understood as all positive.
For my matters I just needed a positive and a negative file, so I twerk a little the code to force it to work.
In /api/classifiers

if (!req.files) {
        formData = bundleUtils.createFormData(req.body);
      } else {
        formData = { name: req.body.classifiername };
        req.files.classupload.map(function (fileobj, idx) {
          if (idx < 1) {
            formData[req.body.classname[idx] + '_positive_examples'] = fs.createReadStream(path.join(fileobj.destination, fileobj.filename));
          }else{
            formData.negative_examples =fs.createReadStream(path.join(fileobj.destination, fileobj.filename));
          }
        });

        //if (req.files.negativeclassupload && req.files.negativeclassupload.length > 0) {
        //  var negpath = path.join(req.files.negativeclassupload[0].destination, req.files.negativeclassupload[0].filename);
        //  formData.negative_examples = fs.createReadStream(negpath);
        //}
      }

**Comment by germanattanasio** [comment] 2016-06-28 20:10
Cool. I'm closing this since there is no issue to fix

**Comment by walmon** [comment] 2016-06-28 20:11
This is an issue, I created a workaround for me, but the just-forked-code won't work well.

**Comment by kognate** [comment] 2016-06-28 20:38
@german was able to reproduce this,  and there is a fix in #178

**Comment by germanattanasio** [comment] 2016-06-28 20:43
fixed

**Closed by germanattanasio** 2016-06-28 20:43 UTC
